name: Deploy to Server

on:
  push:
    branches:
      - main  # main 브랜치에 push 될 때만 작동

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission to Gradle Wrapper
      run: chmod +x gradlew
      working-directory: back

    - name: Build with Gradle
      run: ./gradlew clean build
      working-directory: back

    - name: Deploy via SCP
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > key.pem
        chmod 600 key.pem
        scp -i key.pem back/build/libs/back-0.0.1-SNAPSHOT.jar $USER@$HOST:/home/ubuntu/.ssh/SCHOOPY-BE/back/build/libs/
        ssh -i key.pem $USER@$HOST "bash /home/ubuntu/.ssh/SCHOOPY-BE/back/build/libs/restart.sh"
        rm -f key.pem
